[package]
name = "libobsidian"
version = "0.0.1"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
serde = { version = "1.0.204", features = ["derive"] }
serde_yaml = "0.9.34"
walkdir = "2.5.0"

[dev-dependencies]
indoc = "2.0.5"
